version: '3.8'

services:
  backend:
    build:
      image: backend:latest
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  nginx:
    build:
      image: nginx:latest
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt:ro
      - ./nginx/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key:ro
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
