services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY} # Pass the environment variable to the Docker build process
    image: ${{ env.DOCKERHUB_USERNAME }}/backend:latest # Tag image with your Docker Hub username
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ${{ env.DOCKERHUB_USERNAME }}/nginx:latest # Tag image with your Docker Hub username
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt:ro
      - ./nginx/ssl/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key:ro
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
