name: Build and Deploy to Docker Hub on Release

on:
  release:
    types: [published]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    
    
    - name: Create SSL certificates from secrets
      run: |
        # Create nginx SSL directory
        mkdir -p ./nginx/ssl
        
        # Write certificates from GitHub secrets to files
        echo "${{ secrets.SSL_CERTIFICATE }}" > ./nginx/ssl/nginx-selfsigned.crt
        echo "${{ secrets.SSL_PRIVATE_KEY }}" > ./nginx/ssl/nginx-selfsigned.key
        
        # Set proper permissions
        chmod 644 ./nginx/ssl/nginx-selfsigned.crt
        chmod 600 ./nginx/ssl/nginx-selfsigned.key
        
    - name: Build with Docker Compose
      env:
        # Pass GitHub secrets as environment variables
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        # Add other secrets as needed
      run: |
        # Build all services defined in docker-compose.yml
        docker compose build
        
    
    - name: Push images to Docker Hub
      run: |
        VERSION=${{ steps.version.outputs.version }}
        
        # Get list of tagged images
        TAGGED_IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "^$DOCKERHUB_USERNAME/")
        
        for IMAGE in $TAGGED_IMAGES; do
          echo "Pushing $IMAGE..."
          docker push $IMAGE
        done
    
    - name: Clean up local images
      run: |
        # Clean up to save space
        docker system prune -f
        
    - name: Deployment Summary
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "🐳 Images pushed to Docker Hub under username: $DOCKERHUB_USERNAME"
     
